export const aboutMeData = {
  id: 'EasyStock',
  img: require('../../images/Grig1.svg').default,
  alt: 'Artem',
  line1: 'My name is Artem Grigorev.',
  line2: 'I\'m full stack developer, work as an expert in blockchain technology, create web/mobile apps and chat bots. I work with SQL and noSQL databases, have 7 years of experince in IT industry.',
  line3: 'I\'m interested in new technologies and study the way they can change our world.',
  line4: 'My practical areas of expertise:',
  line5: <ul><li>e-commerce and digital economy technologies</li><li>Blockchain / DLT</li><li>Cybersecurity</li></ul>,
  line8: 'Work experience ',
  line9: 'e-document management',
  line10: 'In 2014-2016, I was setting up an electronic document management system for quality certificates in one large retail company with a SAP system.',
  line11: 'e-commerce',
  line12: 'In 2016-2017, together with a group of friends, we founded a system of warehouses and points of delivery for electronic stores. I was responsible for digital infrastructure, ERP systems, accounting and much more.',
  line13: 'Video Analitics',
  line14: 'In 2016-2017 I took a training course and worked with video analytics / video semantics systems. Was a regional representative, a technical specialist for setting up and maintaining the system of the SpecLab company.',
  line15: 'RexNote',
  line16: 'In 2017, I was asked to develop corporate contact manager (mobile application and back-end) The client was one law firm. I collected requirements, developed Technical tasks, selected developers team and created a working MVP of a mobile client application in React-native.',
  line17: 'Blockchain / DLT',
  line18: 'In 2017, I headed the R&D direction of the blockchain business association. I created a Research Laboratory the purpose of which was to develop solutions for the implementation of distributed ledger technology (DLT/ Blockchain) in various industries. To solve various business problems, my team and I was creating working product prototypes (MVP). That time, I led teams of 2-4 developers, was engaged in collecting requirements for a product, developing a technical task, was in the role of a team lead, front-end developer, DevOps specialist or full stack developer. Mostly I used the Hyperledger platform and its projects. The Ethereum platform was used less frequently.',
  line19: 'Some laboratory\'s projects:',
  line20: <ul><li> The "university coins and electronic student ID" project for the University of KFU. We created MVP based on Hyperledger Fabric. It was a web service, to which it was planned to connect the Hyperledger blockchain network deployed on the basis of the university infrastructure in the future.</li></ul>,
  line21: <ul><li> Supplychain project to control the  chicken meat supply of one company. An MVP was created based on Hyperledger Fabric. We created web application demonstrating the process of sending invoices and product data.</li></ul>,
  line22: <ul><li> Project of Medical Records based on BlockchainID technology. MVP was created based on Hyperledger Indy.</li></ul>,
  line23: <ul><li> Digital Municipalities project. An MVP of a mobile application was created, which was planned to be deployed based on Sovrin network.</li></ul>,
  line24: 'Mobile App EasyStock',
  line25: 'in 2019, with a friend, we developed a mobile application for monitoring stocks and cryptocurrencies for personal use. Was one of two Fullstack developers.',
  line26: 'Remote Desktop Client',
  line27: 'In January 2020, I developed the “Remote Client” MVP project. Configuring and recording a Linux OS image, creating Systemd services, scripts and client applications for the RDP protocol. (Freelance)',
  line28: 'Blockchain ID for Airlines',
  line29: 'In August 2020, I developed an MVP of a Blockchain ID project based on Hyperledger Indy (Sovrin project) for one startup. The essence of the project is in the reliable confirmation of the analyzes passed by the passengers of the airline. A client program was created in React, a Python backend. (Freelance)',
  line30: 'Freelance projects:',
  line31: '2021 - WebSites on MERN stack (React + Nodejs + Express + MongoDB). Online store with specific ERP functionality.',
  line32: '2021 - Telegram bots (Telegraf + NodeJS + MongoDB). Telegram bots that are assistants for several individual entrepreneurs.',
  line33: 'Stack of technologies I work with:',
  line34: <ul><li>Linux administration</li><li>Linux OS\Server</li><li>JavaScript (main language)</li><li>TypeScript</li><li>Java Core</li><li>Python</li></ul>,
  line35: <ul><li>React</li><li>React-native</li><li>React Hooks</li><li>Redux</li><li>Telegraf (Telegram bots)</li></ul>,
  line36: <ul><li>Nodejs (main technology)</li><li>Express</li><li>Django</li><li>SQL</li><li>Mongoose</li><li>MongoDB</li><li>Docker</li></ul>,
  line37: <ul><li>Hyperledger Fabric (Supply Chain)</li><li>Hyperledger Indy (Blockchain ID)</li><li>Blockchain/DLT</li></ul>,
  line38:  <ul>I am open for cooperation on good projects.<br /> My contacts: </ul>,
  line39: 'My contacts:',
};
